name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Patch and build
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./paper jar
      - uses: actions/upload-artifact@v2
        with:
          name: Paper Launcher
          path: /paperclip.jar